# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-25 07:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('regimens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regimen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(help_text='Any notes to be made on this regimen', verbose_name='Notes')),
                ('date_started', models.DateField(help_text='The date the patient started this regimen', verbose_name='Regimen start date')),
                ('date_ended', models.DateField(blank=True, help_text='The date the patient stopped this regimen. This field is optional', null=True, verbose_name='Regimen end date')),
                ('current_regimen', models.BooleanField(default=True, help_text='Mark this regimen as the current patient regimen or not. By default, it will be marked as the current regimen', verbose_name='Current regimen')),
                ('date_created', models.DateField(auto_now_add=True, help_text='The date the regimen was added to the system')),
                ('date_last_modified', models.DateField(auto_now=True, help_text='The date details of this regimen were most recently updated')),
                ('created_by', models.ForeignKey(blank=True, help_text='The user that added this regimen to the system', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_regimens', related_query_name='created_regimen', to=settings.AUTH_USER_MODEL)),
                ('drugs', models.ManyToManyField(related_name='regimens', related_query_name='regimen', to='regimens.Drug')),
                ('last_modified_by', models.ForeignKey(blank=True, help_text='The user that last modified details of this regimen', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_regimens', related_query_name='modified_regimen', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(help_text='The patient undertaking this regimen', on_delete=django.db.models.deletion.CASCADE, related_name='regimens', related_query_name='regimen', to='patients.Patient')),
            ],
        ),
    ]
