# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-02 18:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome_date', models.DateField(help_text='The date the outcome for the patient was obtained', verbose_name='Outcome date')),
                ('notes', models.TextField(blank=True, help_text='Any information with regards to this patient outcome. This field is optional', null=True, verbose_name='Notes')),
                ('date_created', models.DateField(auto_now_add=True, help_text='The date the outcome was added to the system')),
                ('date_last_modified', models.DateField(auto_now=True, help_text='The date the details of this outcome were last modified')),
                ('created_by', models.ForeignKey(blank=True, help_text='The user that created this patient outcome', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_patient_outcomes', related_query_name='created_patient_outcome', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(blank=True, help_text='The user that last modified details on this patient outcome', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_patient_outcomes', related_query_name='modified_patient_outcome', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OutcomeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The unique name for the patient outcome category', max_length=100, unique=True, verbose_name='Patient outcome name')),
                ('description', models.TextField(help_text='Definition of this patient outcome', verbose_name='Description')),
                ('date_created', models.DateField(auto_now_add=True, help_text='The date this patient outcome type was added to the system')),
                ('date_last_modified', models.DateField(auto_now=True, help_text='The most recent date that details on this outcome type were last modified')),
                ('created_by', models.ForeignKey(blank=True, help_text='The user that added this outcome type to the system', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_patient_outcome_types', related_query_name='created_patient_outcome_type', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(blank=True, help_text='The user that last modified details on this outcome type', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_patient_outcome_types', related_query_name='modified_patient_outcome_type', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='outcome',
            name='outcome_type',
            field=models.ForeignKey(help_text='The category of the patient outcome', on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', related_query_name='outcome', to='patients.OutcomeType', verbose_name='Patient outcome type'),
        ),
        migrations.AddField(
            model_name='outcome',
            name='patient',
            field=models.ForeignKey(help_text='The patient whom the outcome is for', on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', related_query_name='outcome', to='patients.Patient', verbose_name='Patient'),
        ),
    ]
