# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-01 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='archived',
            field=models.BooleanField(default=False, help_text='Whether this patient has been archived', verbose_name='Archived'),
        ),
        migrations.AddField(
            model_name='patient',
            name='second_contact_number',
            field=models.CharField(blank=True, help_text='A second contact number for the patient. This field is optional', max_length=50, null=True, verbose_name='Second contact number'),
        ),
        migrations.AddField(
            model_name='patient',
            name='third_contact_number',
            field=models.CharField(blank=True, help_text='A third contact number for the patient. This field is optional', max_length=50, null=True, verbose_name='Third contact number'),
        ),
    ]
